### PR TITLE
Update to use webbit 0.4.6.

### PR DESCRIPTION
**Pull request by green-coder**

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
I'm no longer so sure about this project, and my latest thoughts about REST in Webbit are reflected in webbit/webbit#62 - which might become a new project under the webbit organization.

**Comment by green-coder** [comment]
I am new on web services and a little lost about which solution to use to get some REST into my project le-moulin-studio/forest. I didn't see webbit/webbit#62 being integrated anywhere.

Currently, which solution or lib is recommended to be used on the top of Netty? Should I use webbit-rest for now?

PS: I found your project from this article : http://www.jerome-bernard.com/blog/2011/12/14/how-to-design-your-next-rest-api/

**Comment by aslakhellesoy** [comment]
It's not integrated anywhere yet.

Not sure how web services is related to this.

On Apr 7, 2012, at 12:29, Vincent Cantin
reply@reply.github.com
wrote:

**Comment by green-coder** [comment]
I used the wrong vocabulary. I meant RESTful web services.

**Pull request closed without merging**
